#!/bin/bash

WORK_DIR="app"
version="v3.2.5"
mkdir -p $WORK_DIR

setup () {
    local zippath
    zippath="$WORK_DIR/master.zip"
    curl -L "https://api.github.com/repos/pokurt/Nana-Remix/zipball/$version?access_token=$github_token" > $zippath
    unzip -qq "$zippath" -d "$WORK_DIR"
    rm -rf "$zippath"
}

start () {
    local bot
    bot=$(cd $WORK_DIR && ls) && mv "$WORK_DIR/$bot" "nana"
    cd "nana"
    python -m nana
}

run () {
    setup
    start
}

run
